/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiAgentExtract : The AI agent to be used for extraction.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiAgentExtract {
    /// The type of AI agent to be used for extraction.
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "long_text", skip_serializing_if = "Option::is_none")]
    pub long_text: Option<Box<models::AiAgentLongTextTool>>,
    #[serde(rename = "basic_text", skip_serializing_if = "Option::is_none")]
    pub basic_text: Option<Box<models::AiAgentBasicTextTool>>,
    #[serde(rename = "basic_image", skip_serializing_if = "Option::is_none")]
    pub basic_image: Option<Box<models::AiAgentBasicTextTool>>,
}

impl AiAgentExtract {
    /// The AI agent to be used for extraction.
    pub fn new(r#type: Type) -> AiAgentExtract {
        AiAgentExtract {
            r#type,
            long_text: None,
            basic_text: None,
            basic_image: None,
        }
    }
}
/// The type of AI agent to be used for extraction.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "ai_agent_extract")]
    AiAgentExtract,
}

impl Default for Type {
    fn default() -> Type {
        Self::AiAgentExtract
    }
}

