/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiAgentLongTextToolAllOfEmbeddingsStrategy {
    /// The strategy used for the AI agent for calculating embeddings.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The number of tokens per chunk.
    #[serde(rename = "num_tokens_per_chunk", skip_serializing_if = "Option::is_none")]
    pub num_tokens_per_chunk: Option<i32>,
}

impl AiAgentLongTextToolAllOfEmbeddingsStrategy {
    pub fn new() -> AiAgentLongTextToolAllOfEmbeddingsStrategy {
        AiAgentLongTextToolAllOfEmbeddingsStrategy {
            id: None,
            num_tokens_per_chunk: None,
        }
    }
}

