/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiAgent : Can be one of the following objects:   * AI agent for questions   * AI agent for text generation   * AI agent for freeform metadata extraction   * AI agent for structured metadata extraction.
/// Can be one of the following objects:   * AI agent for questions   * AI agent for text generation   * AI agent for freeform metadata extraction   * AI agent for structured metadata extraction.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AiAgent {
    AiAgentAsk(Box<models::AiAgentAsk>),
    AiAgentTextGen(Box<models::AiAgentTextGen>),
    AiAgentExtract(Box<models::AiAgentExtract>),
    AiAgentExtractStructured(Box<models::AiAgentExtractStructured>),
}

impl Default for AiAgent {
    fn default() -> Self {
        Self::AiAgentAsk(Default::default())
    }
}
/// The type of AI agent used to handle queries.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "ai_agent_ask")]
    AiAgentAsk,
    #[serde(rename = "ai_agent_text_gen")]
    AiAgentTextGen,
    #[serde(rename = "ai_agent_extract")]
    AiAgentExtract,
    #[serde(rename = "ai_agent_extract_structured")]
    AiAgentExtractStructured,
}

impl Default for Type {
    fn default() -> Type {
        Self::AiAgentAsk
    }
}

