/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiAgentBasicTextToolBase : AI agent processor used to handle basic text.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiAgentBasicTextToolBase {
    /// The model used for the AI agent for basic text. For specific model values, see the [available models list](g://box-ai/supported-models).
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// The number of tokens for completion.
    #[serde(rename = "num_tokens_for_completion", skip_serializing_if = "Option::is_none")]
    pub num_tokens_for_completion: Option<i32>,
    #[serde(rename = "llm_endpoint_params", skip_serializing_if = "Option::is_none")]
    pub llm_endpoint_params: Option<Box<models::AiLlmEndpointParams>>,
}

impl AiAgentBasicTextToolBase {
    /// AI agent processor used to handle basic text.
    pub fn new() -> AiAgentBasicTextToolBase {
        AiAgentBasicTextToolBase {
            model: None,
            num_tokens_for_completion: None,
            llm_endpoint_params: None,
        }
    }
}

