/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiAgentAsk : The AI agent used to handle queries.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiAgentAsk {
    /// The type of AI agent used to handle queries.
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "long_text", skip_serializing_if = "Option::is_none")]
    pub long_text: Option<Box<models::AiAgentLongTextTool>>,
    #[serde(rename = "basic_text", skip_serializing_if = "Option::is_none")]
    pub basic_text: Option<Box<models::AiAgentBasicTextTool>>,
    #[serde(rename = "spreadsheet", skip_serializing_if = "Option::is_none")]
    pub spreadsheet: Option<Box<models::AiAgentSpreadsheetTool>>,
    #[serde(rename = "long_text_multi", skip_serializing_if = "Option::is_none")]
    pub long_text_multi: Option<Box<models::AiAgentLongTextTool>>,
    #[serde(rename = "basic_text_multi", skip_serializing_if = "Option::is_none")]
    pub basic_text_multi: Option<Box<models::AiAgentBasicTextTool>>,
    #[serde(rename = "basic_image", skip_serializing_if = "Option::is_none")]
    pub basic_image: Option<Box<models::AiAgentBasicTextTool>>,
    #[serde(rename = "basic_image_multi", skip_serializing_if = "Option::is_none")]
    pub basic_image_multi: Option<Box<models::AiAgentBasicTextTool>>,
}

impl AiAgentAsk {
    /// The AI agent used to handle queries.
    pub fn new(r#type: Type) -> AiAgentAsk {
        AiAgentAsk {
            r#type,
            long_text: None,
            basic_text: None,
            spreadsheet: None,
            long_text_multi: None,
            basic_text_multi: None,
            basic_image: None,
            basic_image_multi: None,
        }
    }
}
/// The type of AI agent used to handle queries.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "ai_agent_ask")]
    AiAgentAsk,
}

impl Default for Type {
    fn default() -> Type {
        Self::AiAgentAsk
    }
}

