/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiExtractStructuredFieldsInner : The fields to be extracted from the provided items.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiExtractStructuredFieldsInner {
    /// A unique identifier for the field.
    #[serde(rename = "key")]
    pub key: String,
    /// A description of the field.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The display name of the field.
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// The context about the key that may include how to find and format it.
    #[serde(rename = "prompt", skip_serializing_if = "Option::is_none")]
    pub prompt: Option<String>,
    /// The type of the field. It include but is not limited to string, float, date, enum, and multiSelect.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// A list of options for this field. This is most often used in combination with the enum and multiSelect field types.
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<models::AiExtractStructuredFieldsInnerOptionsInner>>,
}

impl AiExtractStructuredFieldsInner {
    /// The fields to be extracted from the provided items.
    pub fn new(key: String) -> AiExtractStructuredFieldsInner {
        AiExtractStructuredFieldsInner {
            key,
            description: None,
            display_name: None,
            prompt: None,
            r#type: None,
            options: None,
        }
    }
}

