/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiItemBase : The item to be processed by the LLM.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiItemBase {
    /// The ID of the file.
    #[serde(rename = "id")]
    pub id: String,
    /// The type of the item. Currently the value can be `file` only.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The content of the item, often the text representation.
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
}

impl AiItemBase {
    /// The item to be processed by the LLM.
    pub fn new(id: String, r#type: Type) -> AiItemBase {
        AiItemBase {
            id,
            r#type,
            content: None,
        }
    }
}
/// The type of the item. Currently the value can be `file` only.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "file")]
    File,
}

impl Default for Type {
    fn default() -> Type {
        Self::File
    }
}

