/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiResponse : AI response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiResponse {
    /// The answer provided by the LLM.
    #[serde(rename = "answer")]
    pub answer: String,
    /// The ISO date formatted timestamp of when the answer to the prompt was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// The reason the response finishes.
    #[serde(rename = "completion_reason", skip_serializing_if = "Option::is_none")]
    pub completion_reason: Option<String>,
    #[serde(rename = "ai_agent_info", skip_serializing_if = "Option::is_none")]
    pub ai_agent_info: Option<Box<models::AiAgentInfo>>,
}

impl AiResponse {
    /// AI response.
    pub fn new(answer: String, created_at: String) -> AiResponse {
        AiResponse {
            answer,
            created_at,
            completion_reason: None,
            ai_agent_info: None,
        }
    }
}

