/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiStudioAgentAsk : The AI agent to be used to handle queries.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiStudioAgentAsk {
    /// The type of AI agent used to handle queries.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The state of the AI Agent capability. Possible values are: `enabled` and `disabled`.
    #[serde(rename = "access_state")]
    pub access_state: String,
    /// The description of the AI agent.
    #[serde(rename = "description")]
    pub description: String,
    /// Custom instructions for the AI agent.
    #[serde(rename = "custom_instructions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_instructions: Option<Option<String>>,
    /// Suggested questions for the AI agent. If null, suggested question will be generated. If empty, no suggested questions will be displayed.
    #[serde(rename = "suggested_questions", skip_serializing_if = "Option::is_none")]
    pub suggested_questions: Option<Vec<String>>,
    #[serde(rename = "long_text", skip_serializing_if = "Option::is_none")]
    pub long_text: Option<Box<models::AiStudioAgentLongTextTool>>,
    #[serde(rename = "basic_text", skip_serializing_if = "Option::is_none")]
    pub basic_text: Option<Box<models::AiStudioAgentBasicTextTool>>,
    #[serde(rename = "basic_image", skip_serializing_if = "Option::is_none")]
    pub basic_image: Option<Box<models::AiStudioAgentBasicTextTool>>,
    #[serde(rename = "spreadsheet", skip_serializing_if = "Option::is_none")]
    pub spreadsheet: Option<Box<models::AiStudioAgentSpreadsheetTool>>,
    #[serde(rename = "long_text_multi", skip_serializing_if = "Option::is_none")]
    pub long_text_multi: Option<Box<models::AiStudioAgentLongTextTool>>,
    #[serde(rename = "basic_text_multi", skip_serializing_if = "Option::is_none")]
    pub basic_text_multi: Option<Box<models::AiStudioAgentBasicTextTool>>,
    #[serde(rename = "basic_image_multi", skip_serializing_if = "Option::is_none")]
    pub basic_image_multi: Option<Box<models::AiStudioAgentBasicTextTool>>,
}

impl AiStudioAgentAsk {
    /// The AI agent to be used to handle queries.
    pub fn new(r#type: Type, access_state: String, description: String) -> AiStudioAgentAsk {
        AiStudioAgentAsk {
            r#type,
            access_state,
            description,
            custom_instructions: None,
            suggested_questions: None,
            long_text: None,
            basic_text: None,
            basic_image: None,
            spreadsheet: None,
            long_text_multi: None,
            basic_text_multi: None,
            basic_image_multi: None,
        }
    }
}
/// The type of AI agent used to handle queries.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "ai_agent_ask")]
    AiAgentAsk,
}

impl Default for Type {
    fn default() -> Type {
        Self::AiAgentAsk
    }
}

