/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiTextGenAgent : The AI agent to be used to handle the AI text generation request.
/// The AI agent to be used to handle the AI text generation request.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AiTextGenAgent {
    AiAgentReference(Box<models::AiAgentReference>),
    AiAgentTextGen(Box<models::AiAgentTextGen>),
}

impl Default for AiTextGenAgent {
    fn default() -> Self {
        Self::AiAgentReference(Default::default())
    }
}
/// The type of AI agent used to handle queries.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "ai_agent_id")]
    AiAgentId,
    #[serde(rename = "ai_agent_text_gen")]
    AiAgentTextGen,
}

impl Default for Type {
    fn default() -> Type {
        Self::AiAgentId
    }
}

