/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AppItemEventSource : The AppItem that triggered an event in the event stream.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppItemEventSource {
    /// The id of the `AppItem`.
    #[serde(rename = "id")]
    pub id: String,
    /// The type of the source that this event represents. Can only be `app_item`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The type of the `AppItem`.
    #[serde(rename = "app_item_type")]
    pub app_item_type: String,
    /// The user that triggered the event.
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::UserMini>>,
    /// The group that triggered the event.
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<Box<models::GroupMini>>,
}

impl AppItemEventSource {
    /// The AppItem that triggered an event in the event stream.
    pub fn new(id: String, r#type: Type, app_item_type: String) -> AppItemEventSource {
        AppItemEventSource {
            id,
            r#type,
            app_item_type,
            user: None,
            group: None,
        }
    }
}
/// The type of the source that this event represents. Can only be `app_item`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "app_item")]
    AppItem,
}

impl Default for Type {
    fn default() -> Type {
        Self::AppItem
    }
}

