/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CollaborationAllowlistExemptTarget : The user that is exempt from any of the restrictions imposed by the list of allowed collaboration domains for this enterprise.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollaborationAllowlistExemptTarget {
    /// The unique identifier for this exemption.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The value will always be `collaboration_whitelist_exempt_target`.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "enterprise", skip_serializing_if = "Option::is_none")]
    pub enterprise: Option<Box<models::CollaborationAllowlistExemptTargetEnterprise>>,
    /// The user that has been exempt.
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::UserMini>>,
    /// The time the entry was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// The time the entry was modified.
    #[serde(rename = "modified_at", skip_serializing_if = "Option::is_none")]
    pub modified_at: Option<String>,
}

impl CollaborationAllowlistExemptTarget {
    /// The user that is exempt from any of the restrictions imposed by the list of allowed collaboration domains for this enterprise.
    pub fn new() -> CollaborationAllowlistExemptTarget {
        CollaborationAllowlistExemptTarget {
            id: None,
            r#type: None,
            enterprise: None,
            user: None,
            created_at: None,
            modified_at: None,
        }
    }
}
/// The value will always be `collaboration_whitelist_exempt_target`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "collaboration_whitelist_exempt_target")]
    CollaborationWhitelistExemptTarget,
}

impl Default for Type {
    fn default() -> Type {
        Self::CollaborationWhitelistExemptTarget
    }
}

