/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateAiAgent : The schema for AI agent create request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAiAgent {
    /// The type of agent used to handle queries.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The name of the AI Agent.
    #[serde(rename = "name")]
    pub name: String,
    /// The state of the AI Agent. Possible values are: `enabled`, `disabled`, and `enabled_for_selected_users`.
    #[serde(rename = "access_state")]
    pub access_state: String,
    /// The icon reference of the AI Agent. It should have format of the URL `https://cdn01.boxcdn.net/app-assets/aistudio/avatars/<file_name>` where possible values of `file_name` are: `logo_boxAi.png`,`logo_stamp.png`,`logo_legal.png`,`logo_finance.png`,`logo_config.png`,`logo_handshake.png`,`logo_analytics.png`,`logo_classification.png`.
    #[serde(rename = "icon_reference", skip_serializing_if = "Option::is_none")]
    pub icon_reference: Option<String>,
    /// List of allowed users or groups.
    #[serde(rename = "allowed_entities", skip_serializing_if = "Option::is_none")]
    pub allowed_entities: Option<Vec<models::AiAgentAllowedEntity>>,
    #[serde(rename = "ask", skip_serializing_if = "Option::is_none")]
    pub ask: Option<Box<models::AiStudioAgentAsk>>,
    #[serde(rename = "text_gen", skip_serializing_if = "Option::is_none")]
    pub text_gen: Option<Box<models::AiStudioAgentTextGen>>,
    #[serde(rename = "extract", skip_serializing_if = "Option::is_none")]
    pub extract: Option<Box<models::AiStudioAgentExtract>>,
}

impl CreateAiAgent {
    /// The schema for AI agent create request.
    pub fn new(r#type: Type, name: String, access_state: String) -> CreateAiAgent {
        CreateAiAgent {
            r#type,
            name,
            access_state,
            icon_reference: None,
            allowed_entities: None,
            ask: None,
            text_gen: None,
            extract: None,
        }
    }
}
/// The type of agent used to handle queries.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "ai_agent")]
    AiAgent,
}

impl Default for Type {
    fn default() -> Type {
        Self::AiAgent
    }
}

