/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Event : The description of an event that happened within Box.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Event {
    /// The value will always be `event`.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// When the event object was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// When the event object was recorded in database.
    #[serde(rename = "recorded_at", skip_serializing_if = "Option::is_none")]
    pub recorded_at: Option<String>,
    /// The ID of the event object. You can use this to detect duplicate events.
    #[serde(rename = "event_id", skip_serializing_if = "Option::is_none")]
    pub event_id: Option<String>,
    /// The user that performed the action represented by the event. Some events may be performed by users not logged into Box. In that case, not all attributes of the object are populated and the event is attributed to a unknown user (`user_id = 2`).
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Box<models::UserMini>>,
    /// An event type that can trigger an event.
    #[serde(rename = "event_type", skip_serializing_if = "Option::is_none")]
    pub event_type: Option<EventType>,
    /// The session of the user that performed the action. Not all events will populate this attribute.
    #[serde(rename = "session_id", skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    /// The resource that triggered this event. For more information, check out the guide on event triggers.
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Box<models::EventSourceResource>>,
    /// This object provides additional information about the event if available.  This can include how a user performed an event as well as additional information to correlate an event to external KeySafe logs. Not all events have an `additional_details` object.  This object is only available in the Enterprise Events.
    #[serde(rename = "additional_details", skip_serializing_if = "Option::is_none")]
    pub additional_details: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl Event {
    /// The description of an event that happened within Box.
    pub fn new() -> Event {
        Event {
            r#type: None,
            created_at: None,
            recorded_at: None,
            event_id: None,
            created_by: None,
            event_type: None,
            session_id: None,
            source: None,
            additional_details: None,
        }
    }
}
/// An event type that can trigger an event.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventType {
    #[serde(rename = "ACCESS_GRANTED")]
    AccessGranted,
    #[serde(rename = "ACCESS_REVOKED")]
    AccessRevoked,
    #[serde(rename = "ADD_DEVICE_ASSOCIATION")]
    AddDeviceAssociation,
    #[serde(rename = "ADD_LOGIN_ACTIVITY_DEVICE")]
    AddLoginActivityDevice,
    #[serde(rename = "ADMIN_LOGIN")]
    AdminLogin,
    #[serde(rename = "APPLICATION_CREATED")]
    ApplicationCreated,
    #[serde(rename = "APPLICATION_PUBLIC_KEY_ADDED")]
    ApplicationPublicKeyAdded,
    #[serde(rename = "APPLICATION_PUBLIC_KEY_DELETED")]
    ApplicationPublicKeyDeleted,
    #[serde(rename = "CHANGE_ADMIN_ROLE")]
    ChangeAdminRole,
    #[serde(rename = "CHANGE_FOLDER_PERMISSION")]
    ChangeFolderPermission,
    #[serde(rename = "COLLABORATION_ACCEPT")]
    CollaborationAccept,
    #[serde(rename = "COLLABORATION_EXPIRATION")]
    CollaborationExpiration,
    #[serde(rename = "COLLABORATION_INVITE")]
    CollaborationInvite,
    #[serde(rename = "COLLABORATION_REMOVE")]
    CollaborationRemove,
    #[serde(rename = "COLLABORATION_ROLE_CHANGE")]
    CollaborationRoleChange,
    #[serde(rename = "COLLAB_ADD_COLLABORATOR")]
    CollabAddCollaborator,
    #[serde(rename = "COLLAB_INVITE_COLLABORATOR")]
    CollabInviteCollaborator,
    #[serde(rename = "COLLAB_REMOVE_COLLABORATOR")]
    CollabRemoveCollaborator,
    #[serde(rename = "COLLAB_ROLE_CHANGE")]
    CollabRoleChange,
    #[serde(rename = "COMMENT_CREATE")]
    CommentCreate,
    #[serde(rename = "COMMENT_DELETE")]
    CommentDelete,
    #[serde(rename = "CONTENT_ACCESS")]
    ContentAccess,
    #[serde(rename = "CONTENT_WORKFLOW_ABNORMAL_DOWNLOAD_ACTIVITY")]
    ContentWorkflowAbnormalDownloadActivity,
    #[serde(rename = "CONTENT_WORKFLOW_AUTOMATION_ADD")]
    ContentWorkflowAutomationAdd,
    #[serde(rename = "CONTENT_WORKFLOW_AUTOMATION_DELETE")]
    ContentWorkflowAutomationDelete,
    #[serde(rename = "CONTENT_WORKFLOW_POLICY_ADD")]
    ContentWorkflowPolicyAdd,
    #[serde(rename = "CONTENT_WORKFLOW_SHARING_POLICY_VIOLATION")]
    ContentWorkflowSharingPolicyViolation,
    #[serde(rename = "CONTENT_WORKFLOW_UPLOAD_POLICY_VIOLATION")]
    ContentWorkflowUploadPolicyViolation,
    #[serde(rename = "COPY")]
    Copy,
    #[serde(rename = "DATA_RETENTION_CREATE_RETENTION")]
    DataRetentionCreateRetention,
    #[serde(rename = "DATA_RETENTION_REMOVE_RETENTION")]
    DataRetentionRemoveRetention,
    #[serde(rename = "DELETE")]
    Delete,
    #[serde(rename = "DELETE_USER")]
    DeleteUser,
    #[serde(rename = "DEVICE_TRUST_CHECK_FAILED")]
    DeviceTrustCheckFailed,
    #[serde(rename = "DOWNLOAD")]
    Download,
    #[serde(rename = "EDIT")]
    Edit,
    #[serde(rename = "EDIT_USER")]
    EditUser,
    #[serde(rename = "EDR_CROWDSTRIKE_DEVICE_DETECTED")]
    EdrCrowdstrikeDeviceDetected,
    #[serde(rename = "EDR_CROWDSTRIKE_NO_BOX_TOOLS")]
    EdrCrowdstrikeNoBoxTools,
    #[serde(rename = "EDR_CROWDSTRIKE_BOX_TOOLS_OUTDATED")]
    EdrCrowdstrikeBoxToolsOutdated,
    #[serde(rename = "EDR_CROWDSTRIKE_DRIVE_OUTDATED")]
    EdrCrowdstrikeDriveOutdated,
    #[serde(rename = "EDR_CROWDSTRIKE_ACCESS_ALLOWED_NO_CROWDSTRIKE_DEVICE")]
    EdrCrowdstrikeAccessAllowedNoCrowdstrikeDevice,
    #[serde(rename = "EDR_CROWDSTRIKE_ACCESS_REVOKED")]
    EdrCrowdstrikeAccessRevoked,
    #[serde(rename = "EMAIL_ALIAS_CONFIRM")]
    EmailAliasConfirm,
    #[serde(rename = "EMAIL_ALIAS_REMOVE")]
    EmailAliasRemove,
    #[serde(rename = "ENABLE_TWO_FACTOR_AUTH")]
    EnableTwoFactorAuth,
    #[serde(rename = "ENTERPRISE_APP_AUTHORIZATION_UPDATE")]
    EnterpriseAppAuthorizationUpdate,
    #[serde(rename = "FAILED_LOGIN")]
    FailedLogin,
    #[serde(rename = "FILE_MARKED_MALICIOUS")]
    FileMarkedMalicious,
    #[serde(rename = "FILE_WATERMARKED_DOWNLOAD")]
    FileWatermarkedDownload,
    #[serde(rename = "GROUP_ADD_ITEM")]
    GroupAddItem,
    #[serde(rename = "GROUP_ADD_USER")]
    GroupAddUser,
    #[serde(rename = "GROUP_CREATION")]
    GroupCreation,
    #[serde(rename = "GROUP_DELETION")]
    GroupDeletion,
    #[serde(rename = "GROUP_EDITED")]
    GroupEdited,
    #[serde(rename = "GROUP_REMOVE_ITEM")]
    GroupRemoveItem,
    #[serde(rename = "GROUP_REMOVE_USER")]
    GroupRemoveUser,
    #[serde(rename = "ITEM_COPY")]
    ItemCopy,
    #[serde(rename = "ITEM_CREATE")]
    ItemCreate,
    #[serde(rename = "ITEM_DOWNLOAD")]
    ItemDownload,
    #[serde(rename = "ITEM_EMAIL_SEND")]
    ItemEmailSend,
    #[serde(rename = "ITEM_MAKE_CURRENT_VERSION")]
    ItemMakeCurrentVersion,
    #[serde(rename = "ITEM_MODIFY")]
    ItemModify,
    #[serde(rename = "ITEM_MOVE")]
    ItemMove,
    #[serde(rename = "ITEM_OPEN")]
    ItemOpen,
    #[serde(rename = "ITEM_PREVIEW")]
    ItemPreview,
    #[serde(rename = "ITEM_RENAME")]
    ItemRename,
    #[serde(rename = "ITEM_SHARED")]
    ItemShared,
    #[serde(rename = "ITEM_SHARED_CREATE")]
    ItemSharedCreate,
    #[serde(rename = "ITEM_SHARED_UNSHARE")]
    ItemSharedUnshare,
    #[serde(rename = "ITEM_SHARED_UPDATE")]
    ItemSharedUpdate,
    #[serde(rename = "ITEM_SYNC")]
    ItemSync,
    #[serde(rename = "ITEM_TRASH")]
    ItemTrash,
    #[serde(rename = "ITEM_UNDELETE_VIA_TRASH")]
    ItemUndeleteViaTrash,
    #[serde(rename = "ITEM_UNSYNC")]
    ItemUnsync,
    #[serde(rename = "ITEM_UPLOAD")]
    ItemUpload,
    #[serde(rename = "LEGAL_HOLD_ASSIGNMENT_CREATE")]
    LegalHoldAssignmentCreate,
    #[serde(rename = "LEGAL_HOLD_ASSIGNMENT_DELETE")]
    LegalHoldAssignmentDelete,
    #[serde(rename = "LEGAL_HOLD_POLICY_CREATE")]
    LegalHoldPolicyCreate,
    #[serde(rename = "LEGAL_HOLD_POLICY_DELETE")]
    LegalHoldPolicyDelete,
    #[serde(rename = "LEGAL_HOLD_POLICY_UPDATE")]
    LegalHoldPolicyUpdate,
    #[serde(rename = "LOCK")]
    Lock,
    #[serde(rename = "LOCK_CREATE")]
    LockCreate,
    #[serde(rename = "LOCK_DESTROY")]
    LockDestroy,
    #[serde(rename = "LOGIN")]
    Login,
    #[serde(rename = "MASTER_INVITE_ACCEPT")]
    MasterInviteAccept,
    #[serde(rename = "MASTER_INVITE_REJECT")]
    MasterInviteReject,
    #[serde(rename = "METADATA_INSTANCE_CREATE")]
    MetadataInstanceCreate,
    #[serde(rename = "METADATA_INSTANCE_DELETE")]
    MetadataInstanceDelete,
    #[serde(rename = "METADATA_INSTANCE_UPDATE")]
    MetadataInstanceUpdate,
    #[serde(rename = "METADATA_TEMPLATE_CREATE")]
    MetadataTemplateCreate,
    #[serde(rename = "METADATA_TEMPLATE_DELETE")]
    MetadataTemplateDelete,
    #[serde(rename = "METADATA_TEMPLATE_UPDATE")]
    MetadataTemplateUpdate,
    #[serde(rename = "MOVE")]
    Move,
    #[serde(rename = "NEW_USER")]
    NewUser,
    #[serde(rename = "PREVIEW")]
    Preview,
    #[serde(rename = "REMOVE_DEVICE_ASSOCIATION")]
    RemoveDeviceAssociation,
    #[serde(rename = "REMOVE_LOGIN_ACTIVITY_DEVICE")]
    RemoveLoginActivityDevice,
    #[serde(rename = "RENAME")]
    Rename,
    #[serde(rename = "RETENTION_POLICY_ASSIGNMENT_ADD")]
    RetentionPolicyAssignmentAdd,
    #[serde(rename = "SHARE")]
    Share,
    #[serde(rename = "SHARED_LINK_SEND")]
    SharedLinkSend,
    #[serde(rename = "SHARE_EXPIRATION")]
    ShareExpiration,
    #[serde(rename = "SHIELD_ALERT")]
    ShieldAlert,
    #[serde(rename = "SHIELD_EXTERNAL_COLLAB_ACCESS_BLOCKED")]
    ShieldExternalCollabAccessBlocked,
    #[serde(rename = "SHIELD_EXTERNAL_COLLAB_ACCESS_BLOCKED_MISSING_JUSTIFICATION")]
    ShieldExternalCollabAccessBlockedMissingJustification,
    #[serde(rename = "SHIELD_EXTERNAL_COLLAB_INVITE_BLOCKED")]
    ShieldExternalCollabInviteBlocked,
    #[serde(rename = "SHIELD_EXTERNAL_COLLAB_INVITE_BLOCKED_MISSING_JUSTIFICATION")]
    ShieldExternalCollabInviteBlockedMissingJustification,
    #[serde(rename = "SHIELD_JUSTIFICATION_APPROVAL")]
    ShieldJustificationApproval,
    #[serde(rename = "SHIELD_SHARED_LINK_ACCESS_BLOCKED")]
    ShieldSharedLinkAccessBlocked,
    #[serde(rename = "SHIELD_SHARED_LINK_STATUS_RESTRICTED_ON_CREATE")]
    ShieldSharedLinkStatusRestrictedOnCreate,
    #[serde(rename = "SHIELD_SHARED_LINK_STATUS_RESTRICTED_ON_UPDATE")]
    ShieldSharedLinkStatusRestrictedOnUpdate,
    #[serde(rename = "SIGN_DOCUMENT_ASSIGNED")]
    SignDocumentAssigned,
    #[serde(rename = "SIGN_DOCUMENT_CANCELLED")]
    SignDocumentCancelled,
    #[serde(rename = "SIGN_DOCUMENT_COMPLETED")]
    SignDocumentCompleted,
    #[serde(rename = "SIGN_DOCUMENT_CONVERTED")]
    SignDocumentConverted,
    #[serde(rename = "SIGN_DOCUMENT_CREATED")]
    SignDocumentCreated,
    #[serde(rename = "SIGN_DOCUMENT_DECLINED")]
    SignDocumentDeclined,
    #[serde(rename = "SIGN_DOCUMENT_EXPIRED")]
    SignDocumentExpired,
    #[serde(rename = "SIGN_DOCUMENT_SIGNED")]
    SignDocumentSigned,
    #[serde(rename = "SIGN_DOCUMENT_VIEWED_BY_SIGNED")]
    SignDocumentViewedBySigned,
    #[serde(rename = "SIGNER_DOWNLOADED")]
    SignerDownloaded,
    #[serde(rename = "SIGNER_FORWARDED")]
    SignerForwarded,
    #[serde(rename = "STORAGE_EXPIRATION")]
    StorageExpiration,
    #[serde(rename = "TAG_ITEM_CREATE")]
    TagItemCreate,
    #[serde(rename = "TASK_ASSIGNMENT_CREATE")]
    TaskAssignmentCreate,
    #[serde(rename = "TASK_ASSIGNMENT_DELETE")]
    TaskAssignmentDelete,
    #[serde(rename = "TASK_ASSIGNMENT_UPDATE")]
    TaskAssignmentUpdate,
    #[serde(rename = "TASK_CREATE")]
    TaskCreate,
    #[serde(rename = "TASK_UPDATE")]
    TaskUpdate,
    #[serde(rename = "TERMS_OF_SERVICE_ACCEPT")]
    TermsOfServiceAccept,
    #[serde(rename = "TERMS_OF_SERVICE_REJECT")]
    TermsOfServiceReject,
    #[serde(rename = "UNDELETE")]
    Undelete,
    #[serde(rename = "UNLOCK")]
    Unlock,
    #[serde(rename = "UNSHARE")]
    Unshare,
    #[serde(rename = "UPDATE_COLLABORATION_EXPIRATION")]
    UpdateCollaborationExpiration,
    #[serde(rename = "UPDATE_SHARE_EXPIRATION")]
    UpdateShareExpiration,
    #[serde(rename = "UPLOAD")]
    Upload,
    #[serde(rename = "USER_AUTHENTICATE_OAUTH2_ACCESS_TOKEN_CREATE")]
    UserAuthenticateOauth2AccessTokenCreate,
    #[serde(rename = "WATERMARK_LABEL_CREATE")]
    WatermarkLabelCreate,
    #[serde(rename = "WATERMARK_LABEL_DELETE")]
    WatermarkLabelDelete,
}

impl Default for EventType {
    fn default() -> EventType {
        Self::AccessGranted
    }
}

