/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Events : A list of event objects.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Events {
    /// The number of events returned in this response.
    #[serde(rename = "chunk_size", skip_serializing_if = "Option::is_none")]
    pub chunk_size: Option<i64>,
    #[serde(rename = "next_stream_position", skip_serializing_if = "Option::is_none")]
    pub next_stream_position: Option<Box<models::EventsNextStreamPosition>>,
    /// A list of events.
    #[serde(rename = "entries", skip_serializing_if = "Option::is_none")]
    pub entries: Option<Vec<models::Event>>,
}

impl Events {
    /// A list of event objects.
    pub fn new() -> Events {
        Events {
            chunk_size: None,
            next_stream_position: None,
            entries: None,
        }
    }
}

