/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileFullAllOfExpiringEmbedLink : Requesting this field creates an expiring Box Embed URL for an embedded preview session in an `iframe`.  This URL will expire after 60 seconds and the session will expire after 60 minutes.  Not all file types are supported for these embed URLs. Box Embed is not optimized for mobile browsers and should not be used in web experiences designed for mobile devices. Many UI elements, like the **download** and **print** options might not show in mobile browsers.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileFullAllOfExpiringEmbedLink {
    /// The requested access token.
    #[serde(rename = "access_token", skip_serializing_if = "Option::is_none")]
    pub access_token: Option<String>,
    /// The time in seconds by which this token will expire.
    #[serde(rename = "expires_in", skip_serializing_if = "Option::is_none")]
    pub expires_in: Option<i64>,
    /// The type of access token returned.
    #[serde(rename = "token_type", skip_serializing_if = "Option::is_none")]
    pub token_type: Option<TokenType>,
    /// The permissions that this access token permits, providing a list of resources (files, folders, etc) and the scopes permitted for each of those resources.
    #[serde(rename = "restricted_to", skip_serializing_if = "Option::is_none")]
    pub restricted_to: Option<Vec<models::ResourceScope>>,
    /// The actual expiring embed URL for this file, constructed from the file ID and access tokens specified in this object.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl FileFullAllOfExpiringEmbedLink {
    /// Requesting this field creates an expiring Box Embed URL for an embedded preview session in an `iframe`.  This URL will expire after 60 seconds and the session will expire after 60 minutes.  Not all file types are supported for these embed URLs. Box Embed is not optimized for mobile browsers and should not be used in web experiences designed for mobile devices. Many UI elements, like the **download** and **print** options might not show in mobile browsers.
    pub fn new() -> FileFullAllOfExpiringEmbedLink {
        FileFullAllOfExpiringEmbedLink {
            access_token: None,
            expires_in: None,
            token_type: None,
            restricted_to: None,
            url: None,
        }
    }
}
/// The type of access token returned.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TokenType {
    #[serde(rename = "bearer")]
    Bearer,
}

impl Default for TokenType {
    fn default() -> TokenType {
        Self::Bearer
    }
}

