/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileVersionBase : The bare basic representation of a file version, the minimal amount of fields returned when using the `fields` query parameter.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileVersionBase {
    /// The unique identifier that represent a file version.
    #[serde(rename = "id")]
    pub id: String,
    /// The value will always be `file_version`.
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl FileVersionBase {
    /// The bare basic representation of a file version, the minimal amount of fields returned when using the `fields` query parameter.
    pub fn new(id: String, r#type: Type) -> FileVersionBase {
        FileVersionBase {
            id,
            r#type,
        }
    }
}
/// The value will always be `file_version`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "file_version")]
    FileVersion,
}

impl Default for Type {
    fn default() -> Type {
        Self::FileVersion
    }
}

