/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileVersionLegalHold : File version legal hold is an entity representing all holds on a File Version.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileVersionLegalHold {
    /// The unique identifier for this file version legal hold.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The value will always be `file_version_legal_hold`.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    /// The file version that is held.
    #[serde(rename = "file_version", skip_serializing_if = "Option::is_none")]
    pub file_version: Option<Box<models::FileVersionMini>>,
    /// The file for the file version held. Note that there is no guarantee that the current version of this file is held.
    #[serde(rename = "file", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub file: Option<Option<Box<models::FileMini>>>,
    /// List of assignments contributing to this Hold.
    #[serde(rename = "legal_hold_policy_assignments", skip_serializing_if = "Option::is_none")]
    pub legal_hold_policy_assignments: Option<Vec<models::LegalHoldPolicyAssignment>>,
    /// Time that this File-Version-Legal-Hold was deleted.
    #[serde(rename = "deleted_at", skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<String>,
}

impl FileVersionLegalHold {
    /// File version legal hold is an entity representing all holds on a File Version.
    pub fn new() -> FileVersionLegalHold {
        FileVersionLegalHold {
            id: None,
            r#type: None,
            file_version: None,
            file: None,
            legal_hold_policy_assignments: None,
            deleted_at: None,
        }
    }
}
/// The value will always be `file_version_legal_hold`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "file_version_legal_hold")]
    FileVersionLegalHold,
}

impl Default for Type {
    fn default() -> Type {
        Self::FileVersionLegalHold
    }
}

