/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GroupFullAllOfPermissions : Describes the permissions that the current user has for this group.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupFullAllOfPermissions {
    /// Specifies if the user can invite the group to collaborate on any items.
    #[serde(rename = "can_invite_as_collaborator", skip_serializing_if = "Option::is_none")]
    pub can_invite_as_collaborator: Option<bool>,
}

impl GroupFullAllOfPermissions {
    /// Describes the permissions that the current user has for this group.
    pub fn new() -> GroupFullAllOfPermissions {
        GroupFullAllOfPermissions {
            can_invite_as_collaborator: None,
        }
    }
}

