/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IntegrationMappingPartnerItemTeams : The schema for an integration mapping mapped item object for type Teams.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntegrationMappingPartnerItemTeams {
    /// Type of the mapped item referenced in `id`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// ID of the mapped item (of type referenced in `type`).
    #[serde(rename = "id")]
    pub id: String,
    /// ID of the tenant that is registered with Microsoft Teams.
    #[serde(rename = "tenant_id")]
    pub tenant_id: String,
}

impl IntegrationMappingPartnerItemTeams {
    /// The schema for an integration mapping mapped item object for type Teams.
    pub fn new(r#type: Type, id: String, tenant_id: String) -> IntegrationMappingPartnerItemTeams {
        IntegrationMappingPartnerItemTeams {
            r#type,
            id,
            tenant_id,
        }
    }
}
/// Type of the mapped item referenced in `id`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "channel")]
    Channel,
    #[serde(rename = "team")]
    Team,
}

impl Default for Type {
    fn default() -> Type {
        Self::Channel
    }
}

