/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Invite : An invite for a user to an enterprise.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Invite {
    /// The unique identifier for this invite.
    #[serde(rename = "id")]
    pub id: String,
    /// The value will always be `invite`.
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "invited_to", skip_serializing_if = "Option::is_none")]
    pub invited_to: Option<Box<models::Enterprise>>,
    #[serde(rename = "actionable_by", skip_serializing_if = "Option::is_none")]
    pub actionable_by: Option<Box<models::UserMini>>,
    #[serde(rename = "invited_by", skip_serializing_if = "Option::is_none")]
    pub invited_by: Option<Box<models::UserMini>>,
    /// The status of the invite.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// When the invite was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// When the invite was modified.
    #[serde(rename = "modified_at", skip_serializing_if = "Option::is_none")]
    pub modified_at: Option<String>,
}

impl Invite {
    /// An invite for a user to an enterprise.
    pub fn new(id: String, r#type: Type) -> Invite {
        Invite {
            id,
            r#type,
            invited_to: None,
            actionable_by: None,
            invited_by: None,
            status: None,
            created_at: None,
            modified_at: None,
        }
    }
}
/// The value will always be `invite`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "invite")]
    Invite,
}

impl Default for Type {
    fn default() -> Type {
        Self::Invite
    }
}

