/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LegalHoldPolicyMini : A mini legal hold policy.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LegalHoldPolicyMini {
    /// The unique identifier for this legal hold policy.
    #[serde(rename = "id")]
    pub id: String,
    /// The value will always be `legal_hold_policy`.
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl LegalHoldPolicyMini {
    /// A mini legal hold policy.
    pub fn new(id: String, r#type: Type) -> LegalHoldPolicyMini {
        LegalHoldPolicyMini {
            id,
            r#type,
        }
    }
}
/// The value will always be `legal_hold_policy`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "legal_hold_policy")]
    LegalHoldPolicy,
}

impl Default for Type {
    fn default() -> Type {
        Self::LegalHoldPolicy
    }
}

