/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Outcome : An instance of an outcome.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Outcome {
    /// ID of a specific outcome.
    #[serde(rename = "id")]
    pub id: String,
    /// Lists collaborators affected by the workflow result.
    #[serde(rename = "collaborators", skip_serializing_if = "Option::is_none")]
    pub collaborators: Option<Box<models::CollaboratorVariable>>,
    /// Determines if an action should be completed by all or any assignees.
    #[serde(rename = "completion_rule", skip_serializing_if = "Option::is_none")]
    pub completion_rule: Option<Box<models::CompletionRuleVariable>>,
    /// Determines if the workflow outcome for a file affects a specific collaborator role.
    #[serde(rename = "file_collaborator_role", skip_serializing_if = "Option::is_none")]
    pub file_collaborator_role: Option<Box<models::RoleVariable>>,
    /// Lists collaborators affected by the task workflow result.
    #[serde(rename = "task_collaborators", skip_serializing_if = "Option::is_none")]
    pub task_collaborators: Option<Box<models::CollaboratorVariable>>,
    /// Determines if the workflow outcome affects a specific collaborator role.
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<Box<models::RoleVariable>>,
}

impl Outcome {
    /// An instance of an outcome.
    pub fn new(id: String) -> Outcome {
        Outcome {
            id,
            collaborators: None,
            completion_rule: None,
            file_collaborator_role: None,
            task_collaborators: None,
            role: None,
        }
    }
}

