/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostCommentsRequest {
    /// The text of the comment.  To mention a user, use the `tagged_message` parameter instead.
    #[serde(rename = "message")]
    pub message: String,
    /// The text of the comment, including `@[user_id:name]` somewhere in the message to mention another user, which will send them an email notification, letting them know they have been mentioned.  The `user_id` is the target user's ID, where the `name` can be any custom phrase. In the Box UI this name will link to the user's profile.  If you are not mentioning another user, use `message` instead.
    #[serde(rename = "tagged_message", skip_serializing_if = "Option::is_none")]
    pub tagged_message: Option<String>,
    #[serde(rename = "item")]
    pub item: Box<models::PostCommentsRequestItem>,
}

impl PostCommentsRequest {
    pub fn new(message: String, item: models::PostCommentsRequestItem) -> PostCommentsRequest {
        PostCommentsRequest {
            message,
            tagged_message: None,
            item: Box::new(item),
        }
    }
}

