/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostWebLinksIdRequestParent : Specifies an optional ID of a folder to restore the web link to when the original folder no longer exists.  Please be aware that this ID will only be used if the original folder no longer exists. Use this ID to provide a fallback location to restore the web link to if the original location has been deleted.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostWebLinksIdRequestParent {
    /// The ID of parent item.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl PostWebLinksIdRequestParent {
    /// Specifies an optional ID of a folder to restore the web link to when the original folder no longer exists.  Please be aware that this ID will only be used if the original folder no longer exists. Use this ID to provide a fallback location to restore the web link to if the original location has been deleted.
    pub fn new() -> PostWebLinksIdRequestParent {
        PostWebLinksIdRequestParent {
            id: None,
        }
    }
}

