/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostTermsOfServiceUserStatusesRequestTos : The terms of service to set the status for.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostTermsOfServiceUserStatusesRequestTos {
    /// The type of object.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The ID of terms of service.
    #[serde(rename = "id")]
    pub id: String,
}

impl PostTermsOfServiceUserStatusesRequestTos {
    /// The terms of service to set the status for.
    pub fn new(r#type: Type, id: String) -> PostTermsOfServiceUserStatusesRequestTos {
        PostTermsOfServiceUserStatusesRequestTos {
            r#type,
            id,
        }
    }
}
/// The type of object.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "terms_of_service")]
    TermsOfService,
}

impl Default for Type {
    fn default() -> Type {
        Self::TermsOfService
    }
}

