/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostShieldInformationBarrierSegmentRestrictionsRequest {
    /// The type of the shield barrier segment restriction for this member.
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "shield_information_barrier", skip_serializing_if = "Option::is_none")]
    pub shield_information_barrier: Option<Box<models::ShieldInformationBarrierBase>>,
    #[serde(rename = "shield_information_barrier_segment")]
    pub shield_information_barrier_segment: Box<models::PostShieldInformationBarrierSegmentRestrictionsRequestShieldInformationBarrierSegment>,
    #[serde(rename = "restricted_segment")]
    pub restricted_segment: Box<models::PostShieldInformationBarrierSegmentRestrictionsRequestRestrictedSegment>,
}

impl PostShieldInformationBarrierSegmentRestrictionsRequest {
    pub fn new(r#type: Type, shield_information_barrier_segment: models::PostShieldInformationBarrierSegmentRestrictionsRequestShieldInformationBarrierSegment, restricted_segment: models::PostShieldInformationBarrierSegmentRestrictionsRequestRestrictedSegment) -> PostShieldInformationBarrierSegmentRestrictionsRequest {
        PostShieldInformationBarrierSegmentRestrictionsRequest {
            r#type,
            shield_information_barrier: None,
            shield_information_barrier_segment: Box::new(shield_information_barrier_segment),
            restricted_segment: Box::new(restricted_segment),
        }
    }
}
/// The type of the shield barrier segment restriction for this member.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "shield_information_barrier_segment_restriction")]
    ShieldInformationBarrierSegmentRestriction,
}

impl Default for Type {
    fn default() -> Type {
        Self::ShieldInformationBarrierSegmentRestriction
    }
}

