/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostInvitesRequest {
    #[serde(rename = "enterprise")]
    pub enterprise: Box<models::PostInvitesRequestEnterprise>,
    #[serde(rename = "actionable_by")]
    pub actionable_by: Box<models::PostInvitesRequestActionableBy>,
}

impl PostInvitesRequest {
    pub fn new(enterprise: models::PostInvitesRequestEnterprise, actionable_by: models::PostInvitesRequestActionableBy) -> PostInvitesRequest {
        PostInvitesRequest {
            enterprise: Box::new(enterprise),
            actionable_by: Box::new(actionable_by),
        }
    }
}

