/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostRetentionPolicyAssignmentsRequestAssignTo : The item to assign the policy to.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostRetentionPolicyAssignmentsRequestAssignTo {
    /// The type of item to assign the policy to.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The ID of item to assign the policy to. Set to `null` or omit when `type` is set to `enterprise`.
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
}

impl PostRetentionPolicyAssignmentsRequestAssignTo {
    /// The item to assign the policy to.
    pub fn new(r#type: Type) -> PostRetentionPolicyAssignmentsRequestAssignTo {
        PostRetentionPolicyAssignmentsRequestAssignTo {
            r#type,
            id: None,
        }
    }
}
/// The type of item to assign the policy to.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "enterprise")]
    Enterprise,
    #[serde(rename = "folder")]
    Folder,
    #[serde(rename = "metadata_template")]
    MetadataTemplate,
}

impl Default for Type {
    fn default() -> Type {
        Self::Enterprise
    }
}

