/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PutWebLinksIdRequestParent : The new parent folder to put the web link in. Use this to move the web link to a different folder.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutWebLinksIdRequestParent {
    /// The ID of parent item.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The input for `user_id` is optional. Moving to non-root folder is not allowed when `user_id` is present. Parent folder id should be zero when `user_id` is provided.
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

impl PutWebLinksIdRequestParent {
    /// The new parent folder to put the web link in. Use this to move the web link to a different folder.
    pub fn new() -> PutWebLinksIdRequestParent {
        PutWebLinksIdRequestParent {
            id: None,
            user_id: None,
        }
    }
}

