/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PutFilesIdMetadataEnterpriseSecurityClassification6VmVochwUwoRequestInner : The operation to perform on the classification metadata template instance. In this case, it use used to replace the value stored for the `Box__Security__Classification__Key` field with a new value.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutFilesIdMetadataEnterpriseSecurityClassification6VmVochwUwoRequestInner {
    /// The value will always be `replace`.
    #[serde(rename = "op")]
    pub op: Op,
    /// Defines classifications  available in the enterprise.
    #[serde(rename = "path")]
    pub path: Path,
    /// The name of the classification to apply to this file.  To list the available classifications in an enterprise, use the classification API to retrieve the [classification template](e://get_metadata_templates_enterprise_securityClassification-6VMVochwUWo_schema) which lists all available classification keys.
    #[serde(rename = "value")]
    pub value: String,
}

impl PutFilesIdMetadataEnterpriseSecurityClassification6VmVochwUwoRequestInner {
    /// The operation to perform on the classification metadata template instance. In this case, it use used to replace the value stored for the `Box__Security__Classification__Key` field with a new value.
    pub fn new(op: Op, path: Path, value: String) -> PutFilesIdMetadataEnterpriseSecurityClassification6VmVochwUwoRequestInner {
        PutFilesIdMetadataEnterpriseSecurityClassification6VmVochwUwoRequestInner {
            op,
            path,
            value,
        }
    }
}
/// The value will always be `replace`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Op {
    #[serde(rename = "replace")]
    Replace,
}

impl Default for Op {
    fn default() -> Op {
        Self::Replace
    }
}
/// Defines classifications  available in the enterprise.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Path {
    #[serde(rename = "/Box__Security__Classification__Key")]
    SlashBoxSecurityClassificationKey,
}

impl Default for Path {
    fn default() -> Path {
        Self::SlashBoxSecurityClassificationKey
    }
}

