/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutRetentionPoliciesIdRequest {
    /// The name for the retention policy.
    #[serde(rename = "policy_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub policy_name: Option<Option<String>>,
    /// The additional text description of the retention policy.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "disposition_action", skip_serializing_if = "Option::is_none")]
    pub disposition_action: Option<Box<models::PutRetentionPoliciesIdRequestDispositionAction>>,
    /// Specifies the retention type:  * `modifiable`: You can modify the retention policy. For example, you can add or remove folders, shorten or lengthen the policy duration, or delete the assignment. Use this type if your retention policy is not related to any regulatory purposes. * `non-modifiable`: You can modify the retention policy only in a limited way: add a folder, lengthen the duration, retire the policy, change the disposition action or notification settings. You cannot perform other actions, such as deleting the assignment or shortening the policy duration. Use this type to ensure compliance with regulatory retention policies.  When updating a retention policy, you can use `non-modifiable` type only. You can convert a `modifiable` policy to `non-modifiable`, but not the other way around.
    #[serde(rename = "retention_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub retention_type: Option<Option<String>>,
    #[serde(rename = "retention_length", skip_serializing_if = "Option::is_none")]
    pub retention_length: Option<Box<models::PostRetentionPoliciesRequestRetentionLength>>,
    /// Used to retire a retention policy.  If not retiring a policy, do not include this parameter or set it to `null`.
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
    /// Determines if the owner of items under the policy can extend the retention when the original retention duration is about to end.
    #[serde(rename = "can_owner_extend_retention", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub can_owner_extend_retention: Option<Option<bool>>,
    /// Determines if owners and co-owners of items under the policy are notified when the retention duration is about to end.
    #[serde(rename = "are_owners_notified", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub are_owners_notified: Option<Option<bool>>,
    /// A list of users notified when the retention duration is about to end.
    #[serde(rename = "custom_notification_recipients", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_notification_recipients: Option<Option<Vec<models::UserBase>>>,
}

impl PutRetentionPoliciesIdRequest {
    pub fn new() -> PutRetentionPoliciesIdRequest {
        PutRetentionPoliciesIdRequest {
            policy_name: None,
            description: None,
            disposition_action: None,
            retention_type: None,
            retention_length: None,
            status: None,
            can_owner_extend_retention: None,
            are_owners_notified: None,
            custom_notification_recipients: None,
        }
    }
}

