/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RealtimeServers : A list of real-time servers that can be used for long-polling.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RealtimeServers {
    /// The number of items in this response.
    #[serde(rename = "chunk_size", skip_serializing_if = "Option::is_none")]
    pub chunk_size: Option<i64>,
    /// A list of real-time servers.
    #[serde(rename = "entries", skip_serializing_if = "Option::is_none")]
    pub entries: Option<Vec<models::RealtimeServer>>,
}

impl RealtimeServers {
    /// A list of real-time servers that can be used for long-polling.
    pub fn new() -> RealtimeServers {
        RealtimeServers {
            chunk_size: None,
            entries: None,
        }
    }
}

