/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RetentionPolicyAssignmentAssignedTo : The `type` and `id` of the content that is under retention. The `type` can either be `folder` `enterprise`, or `metadata_template`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetentionPolicyAssignmentAssignedTo {
    /// The ID of the folder, enterprise, or metadata template the policy is assigned to. Set to null or omit when type is set to enterprise.
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    /// The type of resource the policy is assigned to.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl RetentionPolicyAssignmentAssignedTo {
    /// The `type` and `id` of the content that is under retention. The `type` can either be `folder` `enterprise`, or `metadata_template`.
    pub fn new() -> RetentionPolicyAssignmentAssignedTo {
        RetentionPolicyAssignmentAssignedTo {
            id: None,
            r#type: None,
        }
    }
}
/// The type of resource the policy is assigned to.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "folder")]
    Folder,
    #[serde(rename = "enterprise")]
    Enterprise,
    #[serde(rename = "metadata_template")]
    MetadataTemplate,
}

impl Default for Type {
    fn default() -> Type {
        Self::Folder
    }
}

