/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RoleVariable : Determines if the workflow outcome affects a specific collaborator role.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleVariable {
    /// Role object type.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The variable type used by the object.
    #[serde(rename = "variable_type")]
    pub variable_type: VariableType,
    /// The level of access granted.
    #[serde(rename = "variable_value")]
    pub variable_value: VariableValue,
}

impl RoleVariable {
    /// Determines if the workflow outcome affects a specific collaborator role.
    pub fn new(r#type: Type, variable_type: VariableType, variable_value: VariableValue) -> RoleVariable {
        RoleVariable {
            r#type,
            variable_type,
            variable_value,
        }
    }
}
/// Role object type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "variable")]
    Variable,
}

impl Default for Type {
    fn default() -> Type {
        Self::Variable
    }
}
/// The variable type used by the object.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VariableType {
    #[serde(rename = "collaborator_role")]
    CollaboratorRole,
}

impl Default for VariableType {
    fn default() -> VariableType {
        Self::CollaboratorRole
    }
}
/// The level of access granted.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VariableValue {
    #[serde(rename = "editor")]
    Editor,
    #[serde(rename = "viewer")]
    Viewer,
    #[serde(rename = "previewer")]
    Previewer,
    #[serde(rename = "uploader")]
    Uploader,
    #[serde(rename = "previewer uploader")]
    PreviewerUploader,
    #[serde(rename = "viewer uploader")]
    ViewerUploader,
    #[serde(rename = "co-owner")]
    CoOwner,
}

impl Default for VariableValue {
    fn default() -> VariableValue {
        Self::Editor
    }
}

