/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ShieldInformationBarrierSegmentMember : A standard representation of a shield information barrier segment member object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShieldInformationBarrierSegmentMember {
    /// The unique identifier for the shield information barrier segment member.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The type of the shield information barrier segment member.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    /// The `type` and `id` of the requested shield information barrier segment member.
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::UserBase>>,
    #[serde(rename = "shield_information_barrier", skip_serializing_if = "Option::is_none")]
    pub shield_information_barrier: Option<Box<models::ShieldInformationBarrierBase>>,
    #[serde(rename = "shield_information_barrier_segment", skip_serializing_if = "Option::is_none")]
    pub shield_information_barrier_segment: Option<Box<models::ShieldInformationBarrierSegmentMemberAllOfShieldInformationBarrierSegment>>,
    /// ISO date time string when this shield information barrier object was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// The user who created this shield information barrier segment member.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Box<models::UserBase>>,
    /// ISO date time string when this shield information barrier segment Member was updated.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// The user that updated this shield information barrier segment Member.
    #[serde(rename = "updated_by", skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Box<models::UserBase>>,
}

impl ShieldInformationBarrierSegmentMember {
    /// A standard representation of a shield information barrier segment member object.
    pub fn new() -> ShieldInformationBarrierSegmentMember {
        ShieldInformationBarrierSegmentMember {
            id: None,
            r#type: None,
            user: None,
            shield_information_barrier: None,
            shield_information_barrier_segment: None,
            created_at: None,
            created_by: None,
            updated_at: None,
            updated_by: None,
        }
    }
}
/// The type of the shield information barrier segment member.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "shield_information_barrier_segment_member")]
    ShieldInformationBarrierSegmentMember,
}

impl Default for Type {
    fn default() -> Type {
        Self::ShieldInformationBarrierSegmentMember
    }
}

