/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ShieldInformationBarrierSegmentRestriction : A standard representation of a segment restriction of a shield information barrier object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShieldInformationBarrierSegmentRestriction {
    /// Shield information barrier segment restriction.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    /// The unique identifier for the shield information barrier segment restriction.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "shield_information_barrier_segment")]
    pub shield_information_barrier_segment: Box<models::ShieldInformationBarrierSegmentRestrictionMiniAllOfShieldInformationBarrierSegment>,
    #[serde(rename = "restricted_segment")]
    pub restricted_segment: Box<models::ShieldInformationBarrierSegmentRestrictionMiniAllOfRestrictedSegment>,
    #[serde(rename = "shield_information_barrier", skip_serializing_if = "Option::is_none")]
    pub shield_information_barrier: Option<Box<models::ShieldInformationBarrierBase>>,
    /// ISO date time string when this shield information barrier Segment Restriction object was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// The user who created this shield information barrier segment Restriction.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Box<models::UserBase>>,
    /// ISO date time string when this shield information barrier segment Restriction was updated.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// The user that updated this shield information barrier segment Restriction.
    #[serde(rename = "updated_by", skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Box<models::UserBase>>,
}

impl ShieldInformationBarrierSegmentRestriction {
    /// A standard representation of a segment restriction of a shield information barrier object.
    pub fn new(shield_information_barrier_segment: models::ShieldInformationBarrierSegmentRestrictionMiniAllOfShieldInformationBarrierSegment, restricted_segment: models::ShieldInformationBarrierSegmentRestrictionMiniAllOfRestrictedSegment) -> ShieldInformationBarrierSegmentRestriction {
        ShieldInformationBarrierSegmentRestriction {
            r#type: None,
            id: None,
            shield_information_barrier_segment: Box::new(shield_information_barrier_segment),
            restricted_segment: Box::new(restricted_segment),
            shield_information_barrier: None,
            created_at: None,
            created_by: None,
            updated_at: None,
            updated_by: None,
        }
    }
}
/// Shield information barrier segment restriction.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "shield_information_barrier_segment_restriction")]
    ShieldInformationBarrierSegmentRestriction,
}

impl Default for Type {
    fn default() -> Type {
        Self::ShieldInformationBarrierSegmentRestriction
    }
}

