/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ShieldInformationBarrierSegment : A shield information barrier segment object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShieldInformationBarrierSegment {
    /// The unique identifier for the shield information barrier segment.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The type of the shield information barrier segment.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "shield_information_barrier", skip_serializing_if = "Option::is_none")]
    pub shield_information_barrier: Option<Box<models::ShieldInformationBarrierBase>>,
    /// Name of the shield information barrier segment.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Description of the shield information barrier segment.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// ISO date time string when this shield information barrier object was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// The user who created this shield information barrier segment.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Box<models::UserBase>>,
    /// ISO date time string when this shield information barrier segment was updated.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// The user that updated this shield information barrier segment.
    #[serde(rename = "updated_by", skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Box<models::UserBase>>,
}

impl ShieldInformationBarrierSegment {
    /// A shield information barrier segment object.
    pub fn new() -> ShieldInformationBarrierSegment {
        ShieldInformationBarrierSegment {
            id: None,
            r#type: None,
            shield_information_barrier: None,
            name: None,
            description: None,
            created_at: None,
            created_by: None,
            updated_at: None,
            updated_by: None,
        }
    }
}
/// The type of the shield information barrier segment.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "shield_information_barrier_segment")]
    ShieldInformationBarrierSegment,
}

impl Default for Type {
    fn default() -> Type {
        Self::ShieldInformationBarrierSegment
    }
}

