/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SignRequestCreateSigner : The schema for a Signer object used in for creating a Box Sign request object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignRequestCreateSigner {
    /// Email address of the signer. The email address of the signer is required when making signature requests, except when using templates that are configured to include emails.
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<String>>,
    /// Defines the role of the signer in the signature request. A `signer` must sign the document and an `approver` must approve the document. A `final_copy_reader` only receives the final signed document and signing log.
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<Role>,
    /// Used in combination with an embed URL for a sender. After the sender signs, they are redirected to the next `in_person` signer.
    #[serde(rename = "is_in_person", skip_serializing_if = "Option::is_none")]
    pub is_in_person: Option<bool>,
    /// Order of the signer.
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<i32>,
    /// User ID for the signer in an external application responsible for authentication when accessing the embed URL.
    #[serde(rename = "embed_url_external_user_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub embed_url_external_user_id: Option<Option<String>>,
    /// The URL that a signer will be redirected to after signing a document. Defining this URL overrides default or global redirect URL settings for a specific signer. If no declined redirect URL is specified, this URL will be used for decline actions as well.
    #[serde(rename = "redirect_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub redirect_url: Option<Option<String>>,
    /// The URL that a signer will be redirect to after declining to sign a document. Defining this URL overrides default or global declined redirect URL settings for a specific signer.
    #[serde(rename = "declined_redirect_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub declined_redirect_url: Option<Option<String>>,
    /// If set to true, the signer will need to log in to a Box account before signing the request. If the signer does not have an existing account, they will have the option to create a free Box account.
    #[serde(rename = "login_required", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub login_required: Option<Option<bool>>,
    /// If set, this phone number will be used to verify the signer via two-factor authentication before they are able to sign the document. Cannot be selected in combination with `login_required`.
    #[serde(rename = "verification_phone_number", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub verification_phone_number: Option<Option<String>>,
    /// If set, the signer is required to enter the password before they are able to sign a document. This field is write only.
    #[serde(rename = "password", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub password: Option<Option<String>>,
    /// If set, signers who have the same value will be assigned to the same input and to the same signer group. A signer group is not a Box Group. It is an entity that belongs to a Sign Request and can only be used/accessed within this Sign Request. A signer group is expected to have more than one signer. If the provided value is only used for one signer, this value will be ignored and request will be handled as it was intended for an individual signer. The value provided can be any string and only used to determine which signers belongs to same group. A successful response will provide a generated UUID value instead for signers in the same signer group.
    #[serde(rename = "signer_group_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub signer_group_id: Option<Option<String>>,
    /// If true, no emails about the sign request will be sent.
    #[serde(rename = "suppress_notifications", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub suppress_notifications: Option<Option<bool>>,
}

impl SignRequestCreateSigner {
    /// The schema for a Signer object used in for creating a Box Sign request object.
    pub fn new() -> SignRequestCreateSigner {
        SignRequestCreateSigner {
            email: None,
            role: None,
            is_in_person: None,
            order: None,
            embed_url_external_user_id: None,
            redirect_url: None,
            declined_redirect_url: None,
            login_required: None,
            verification_phone_number: None,
            password: None,
            signer_group_id: None,
            suppress_notifications: None,
        }
    }
}
/// Defines the role of the signer in the signature request. A `signer` must sign the document and an `approver` must approve the document. A `final_copy_reader` only receives the final signed document and signing log.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "signer")]
    Signer,
    #[serde(rename = "approver")]
    Approver,
    #[serde(rename = "final_copy_reader")]
    FinalCopyReader,
}

impl Default for Role {
    fn default() -> Role {
        Self::Signer
    }
}

