/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StatusSkillCard : A Box Skill metadata card that puts a status message in the metadata sidebar.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusSkillCard {
    /// The optional date and time this card was created at.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// The value will always be `skill_card`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The value will always be `status`.
    #[serde(rename = "skill_card_type")]
    pub skill_card_type: SkillCardType,
    #[serde(rename = "skill_card_title", skip_serializing_if = "Option::is_none")]
    pub skill_card_title: Option<Box<models::StatusSkillCardSkillCardTitle>>,
    #[serde(rename = "status")]
    pub status: Box<models::StatusSkillCardStatus>,
    #[serde(rename = "skill")]
    pub skill: Box<models::KeywordSkillCardSkill>,
    #[serde(rename = "invocation")]
    pub invocation: Box<models::KeywordSkillCardInvocation>,
}

impl StatusSkillCard {
    /// A Box Skill metadata card that puts a status message in the metadata sidebar.
    pub fn new(r#type: Type, skill_card_type: SkillCardType, status: models::StatusSkillCardStatus, skill: models::KeywordSkillCardSkill, invocation: models::KeywordSkillCardInvocation) -> StatusSkillCard {
        StatusSkillCard {
            created_at: None,
            r#type,
            skill_card_type,
            skill_card_title: None,
            status: Box::new(status),
            skill: Box::new(skill),
            invocation: Box::new(invocation),
        }
    }
}
/// The value will always be `skill_card`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "skill_card")]
    SkillCard,
}

impl Default for Type {
    fn default() -> Type {
        Self::SkillCard
    }
}
/// The value will always be `status`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SkillCardType {
    #[serde(rename = "status")]
    Status,
}

impl Default for SkillCardType {
    fn default() -> SkillCardType {
        Self::Status
    }
}

