/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StoragePolicy : The Storage Policy object describes the storage zone.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoragePolicy {
    /// The unique identifier for this storage policy.
    #[serde(rename = "id")]
    pub id: String,
    /// The value will always be `storage_policy`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// A descriptive name of the region.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl StoragePolicy {
    /// The Storage Policy object describes the storage zone.
    pub fn new(id: String, r#type: Type) -> StoragePolicy {
        StoragePolicy {
            id,
            r#type,
            name: None,
        }
    }
}
/// The value will always be `storage_policy`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "storage_policy")]
    StoragePolicy,
}

impl Default for Type {
    fn default() -> Type {
        Self::StoragePolicy
    }
}

