/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TermsOfServiceBase : The root-level record that is supposed to represent a single Terms of Service.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TermsOfServiceBase {
    /// The unique identifier for this terms of service.
    #[serde(rename = "id")]
    pub id: String,
    /// The value will always be `terms_of_service`.
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl TermsOfServiceBase {
    /// The root-level record that is supposed to represent a single Terms of Service.
    pub fn new(id: String, r#type: Type) -> TermsOfServiceBase {
        TermsOfServiceBase {
            id,
            r#type,
        }
    }
}
/// The value will always be `terms_of_service`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "terms_of_service")]
    TermsOfService,
}

impl Default for Type {
    fn default() -> Type {
        Self::TermsOfService
    }
}

