/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TermsOfServiceUserStatus : The association between a Terms of Service and a user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TermsOfServiceUserStatus {
    /// The unique identifier for this terms of service user status.
    #[serde(rename = "id")]
    pub id: String,
    /// The value will always be `terms_of_service_user_status`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The terms of service.
    #[serde(rename = "tos", skip_serializing_if = "Option::is_none")]
    pub tos: Option<Box<models::TermsOfServiceBase>>,
    /// The user.
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::UserMini>>,
    /// If the user has accepted the terms of services.
    #[serde(rename = "is_accepted", skip_serializing_if = "Option::is_none")]
    pub is_accepted: Option<bool>,
    /// When the legal item was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// When the legal item was modified.
    #[serde(rename = "modified_at", skip_serializing_if = "Option::is_none")]
    pub modified_at: Option<String>,
}

impl TermsOfServiceUserStatus {
    /// The association between a Terms of Service and a user.
    pub fn new(id: String, r#type: Type) -> TermsOfServiceUserStatus {
        TermsOfServiceUserStatus {
            id,
            r#type,
            tos: None,
            user: None,
            is_accepted: None,
            created_at: None,
            modified_at: None,
        }
    }
}
/// The value will always be `terms_of_service_user_status`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "terms_of_service_user_status")]
    TermsOfServiceUserStatus,
}

impl Default for Type {
    fn default() -> Type {
        Self::TermsOfServiceUserStatus
    }
}

