/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`delete_integration_mappings_slack_id`]
#[derive(Clone, Debug)]
pub struct DeleteIntegrationMappingsSlackIdParams {
    /// An ID of an integration mapping.
    pub integration_mapping_id: String
}

/// struct for passing parameters to the method [`delete_integration_mappings_teams_id`]
#[derive(Clone, Debug)]
pub struct DeleteIntegrationMappingsTeamsIdParams {
    /// An ID of an integration mapping.
    pub integration_mapping_id: String
}

/// struct for passing parameters to the method [`get_integration_mappings_slack`]
#[derive(Clone, Debug)]
pub struct GetIntegrationMappingsSlackParams {
    /// Defines the position marker at which to begin returning results. This is used when paginating using marker-based pagination.  This requires `usemarker` to be set to `true`.
    pub marker: Option<String>,
    /// The maximum number of items to return per page.
    pub limit: Option<i64>,
    /// Mapped item type, for which the mapping should be returned.
    pub partner_item_type: Option<String>,
    /// ID of the mapped item, for which the mapping should be returned.
    pub partner_item_id: Option<String>,
    /// Box item ID, for which the mappings should be returned.
    pub box_item_id: Option<String>,
    /// Box item type, for which the mappings should be returned.
    pub box_item_type: Option<String>,
    /// Whether the mapping has been manually created.
    pub is_manually_created: Option<bool>
}

/// struct for passing parameters to the method [`get_integration_mappings_teams`]
#[derive(Clone, Debug)]
pub struct GetIntegrationMappingsTeamsParams {
    /// Mapped item type, for which the mapping should be returned.
    pub partner_item_type: Option<String>,
    /// ID of the mapped item, for which the mapping should be returned.
    pub partner_item_id: Option<String>,
    /// Box item ID, for which the mappings should be returned.
    pub box_item_id: Option<String>,
    /// Box item type, for which the mappings should be returned.
    pub box_item_type: Option<String>
}

/// struct for passing parameters to the method [`post_integration_mappings_slack`]
#[derive(Clone, Debug)]
pub struct PostIntegrationMappingsSlackParams {
    pub integration_mapping_slack_create_request: Option<models::IntegrationMappingSlackCreateRequest>
}

/// struct for passing parameters to the method [`post_integration_mappings_teams`]
#[derive(Clone, Debug)]
pub struct PostIntegrationMappingsTeamsParams {
    pub integration_mapping_teams_create_request: Option<models::IntegrationMappingTeamsCreateRequest>
}

/// struct for passing parameters to the method [`put_integration_mappings_slack_id`]
#[derive(Clone, Debug)]
pub struct PutIntegrationMappingsSlackIdParams {
    /// An ID of an integration mapping.
    pub integration_mapping_id: String,
    /// At least one of `box_item` and `options` must be provided.
    pub put_integration_mappings_slack_id_request: Option<models::PutIntegrationMappingsSlackIdRequest>
}

/// struct for passing parameters to the method [`put_integration_mappings_teams_id`]
#[derive(Clone, Debug)]
pub struct PutIntegrationMappingsTeamsIdParams {
    /// An ID of an integration mapping.
    pub integration_mapping_id: String,
    pub put_integration_mappings_teams_id_request: Option<models::PutIntegrationMappingsTeamsIdRequest>
}


/// struct for typed errors of method [`delete_integration_mappings_slack_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteIntegrationMappingsSlackIdError {
    Status404(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_integration_mappings_teams_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteIntegrationMappingsTeamsIdError {
    Status404(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_integration_mappings_slack`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetIntegrationMappingsSlackError {
    Status400(models::ClientError),
    Status404(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_integration_mappings_teams`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetIntegrationMappingsTeamsError {
    Status400(models::ClientError),
    Status404(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_integration_mappings_slack`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostIntegrationMappingsSlackError {
    Status400(models::ClientError),
    Status404(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_integration_mappings_teams`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostIntegrationMappingsTeamsError {
    Status400(models::ClientError),
    Status404(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`put_integration_mappings_slack_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PutIntegrationMappingsSlackIdError {
    Status400(models::ClientError),
    Status404(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`put_integration_mappings_teams_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PutIntegrationMappingsTeamsIdError {
    Status400(models::ClientError),
    Status404(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}


/// Deletes a [Slack integration mapping](https://support.box.com/hc/en-us/articles/4415585987859-Box-as-the-Content-Layer-for-Slack).   You need Admin or Co-Admin role to use this endpoint.
pub async fn delete_integration_mappings_slack_id(configuration: &configuration::Configuration, params: DeleteIntegrationMappingsSlackIdParams) -> Result<(), Error<DeleteIntegrationMappingsSlackIdError>> {

    let uri_str = format!("{}/integration_mappings/slack/{integration_mapping_id}", configuration.base_path, integration_mapping_id=crate::apis::urlencode(params.integration_mapping_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteIntegrationMappingsSlackIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Deletes a [Teams integration mapping](https://support.box.com/hc/en-us/articles/360044681474-Using-Box-for-Teams). You need Admin or Co-Admin role to use this endpoint.
pub async fn delete_integration_mappings_teams_id(configuration: &configuration::Configuration, params: DeleteIntegrationMappingsTeamsIdParams) -> Result<(), Error<DeleteIntegrationMappingsTeamsIdError>> {

    let uri_str = format!("{}/integration_mappings/teams/{integration_mapping_id}", configuration.base_path, integration_mapping_id=crate::apis::urlencode(params.integration_mapping_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteIntegrationMappingsTeamsIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Lists [Slack integration mappings](https://support.box.com/hc/en-us/articles/4415585987859-Box-as-the-Content-Layer-for-Slack) in a users' enterprise.  You need Admin or Co-Admin role to use this endpoint.
pub async fn get_integration_mappings_slack(configuration: &configuration::Configuration, params: GetIntegrationMappingsSlackParams) -> Result<models::IntegrationMappings, Error<GetIntegrationMappingsSlackError>> {

    let uri_str = format!("{}/integration_mappings/slack", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.marker {
        req_builder = req_builder.query(&[("marker", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.partner_item_type {
        req_builder = req_builder.query(&[("partner_item_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.partner_item_id {
        req_builder = req_builder.query(&[("partner_item_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.box_item_id {
        req_builder = req_builder.query(&[("box_item_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.box_item_type {
        req_builder = req_builder.query(&[("box_item_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.is_manually_created {
        req_builder = req_builder.query(&[("is_manually_created", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IntegrationMappings`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IntegrationMappings`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetIntegrationMappingsSlackError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Lists [Teams integration mappings](https://support.box.com/hc/en-us/articles/360044681474-Using-Box-for-Teams) in a users' enterprise. You need Admin or Co-Admin role to use this endpoint.
pub async fn get_integration_mappings_teams(configuration: &configuration::Configuration, params: GetIntegrationMappingsTeamsParams) -> Result<models::IntegrationMappingsTeams, Error<GetIntegrationMappingsTeamsError>> {

    let uri_str = format!("{}/integration_mappings/teams", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.partner_item_type {
        req_builder = req_builder.query(&[("partner_item_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.partner_item_id {
        req_builder = req_builder.query(&[("partner_item_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.box_item_id {
        req_builder = req_builder.query(&[("box_item_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.box_item_type {
        req_builder = req_builder.query(&[("box_item_type", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IntegrationMappingsTeams`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IntegrationMappingsTeams`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetIntegrationMappingsTeamsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Creates a [Slack integration mapping](https://support.box.com/hc/en-us/articles/4415585987859-Box-as-the-Content-Layer-for-Slack) by mapping a Slack channel to a Box item.  You need Admin or Co-Admin role to use this endpoint.
pub async fn post_integration_mappings_slack(configuration: &configuration::Configuration, params: PostIntegrationMappingsSlackParams) -> Result<models::IntegrationMapping, Error<PostIntegrationMappingsSlackError>> {

    let uri_str = format!("{}/integration_mappings/slack", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.integration_mapping_slack_create_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IntegrationMapping`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IntegrationMapping`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostIntegrationMappingsSlackError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Creates a [Teams integration mapping](https://support.box.com/hc/en-us/articles/360044681474-Using-Box-for-Teams) by mapping a Teams channel to a Box item. You need Admin or Co-Admin role to use this endpoint.
pub async fn post_integration_mappings_teams(configuration: &configuration::Configuration, params: PostIntegrationMappingsTeamsParams) -> Result<models::IntegrationMappingTeams, Error<PostIntegrationMappingsTeamsError>> {

    let uri_str = format!("{}/integration_mappings/teams", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.integration_mapping_teams_create_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IntegrationMappingTeams`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IntegrationMappingTeams`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostIntegrationMappingsTeamsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates a [Slack integration mapping](https://support.box.com/hc/en-us/articles/4415585987859-Box-as-the-Content-Layer-for-Slack). Supports updating the Box folder ID and options.  You need Admin or Co-Admin role to use this endpoint.
pub async fn put_integration_mappings_slack_id(configuration: &configuration::Configuration, params: PutIntegrationMappingsSlackIdParams) -> Result<models::IntegrationMapping, Error<PutIntegrationMappingsSlackIdError>> {

    let uri_str = format!("{}/integration_mappings/slack/{integration_mapping_id}", configuration.base_path, integration_mapping_id=crate::apis::urlencode(params.integration_mapping_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.put_integration_mappings_slack_id_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IntegrationMapping`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IntegrationMapping`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PutIntegrationMappingsSlackIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates a [Teams integration mapping](https://support.box.com/hc/en-us/articles/360044681474-Using-Box-for-Teams). Supports updating the Box folder ID and options. You need Admin or Co-Admin role to use this endpoint.
pub async fn put_integration_mappings_teams_id(configuration: &configuration::Configuration, params: PutIntegrationMappingsTeamsIdParams) -> Result<models::IntegrationMappingTeams, Error<PutIntegrationMappingsTeamsIdError>> {

    let uri_str = format!("{}/integration_mappings/teams/{integration_mapping_id}", configuration.base_path, integration_mapping_id=crate::apis::urlencode(params.integration_mapping_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.put_integration_mappings_teams_id_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IntegrationMappingTeams`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IntegrationMappingTeams`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PutIntegrationMappingsTeamsIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

