/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`delete_legal_hold_policies_id`]
#[derive(Clone, Debug)]
pub struct DeleteLegalHoldPoliciesIdParams {
    /// The ID of the legal hold policy.
    pub legal_hold_policy_id: String
}

/// struct for passing parameters to the method [`get_legal_hold_policies`]
#[derive(Clone, Debug)]
pub struct GetLegalHoldPoliciesParams {
    /// Limits results to policies for which the names start with this search term. This is a case-insensitive prefix.
    pub policy_name: Option<String>,
    /// A comma-separated list of attributes to include in the response. This can be used to request fields that are not normally returned in a standard response.  Be aware that specifying this parameter will have the effect that none of the standard fields are returned in the response unless explicitly specified, instead only fields for the mini representation are returned, additional to the fields requested.
    pub fields: Option<Vec<String>>,
    /// Defines the position marker at which to begin returning results. This is used when paginating using marker-based pagination.  This requires `usemarker` to be set to `true`.
    pub marker: Option<String>,
    /// The maximum number of items to return per page.
    pub limit: Option<i64>
}

/// struct for passing parameters to the method [`get_legal_hold_policies_id`]
#[derive(Clone, Debug)]
pub struct GetLegalHoldPoliciesIdParams {
    /// The ID of the legal hold policy.
    pub legal_hold_policy_id: String
}

/// struct for passing parameters to the method [`post_legal_hold_policies`]
#[derive(Clone, Debug)]
pub struct PostLegalHoldPoliciesParams {
    pub post_legal_hold_policies_request: Option<models::PostLegalHoldPoliciesRequest>
}

/// struct for passing parameters to the method [`put_legal_hold_policies_id`]
#[derive(Clone, Debug)]
pub struct PutLegalHoldPoliciesIdParams {
    /// The ID of the legal hold policy.
    pub legal_hold_policy_id: String,
    pub put_legal_hold_policies_id_request: Option<models::PutLegalHoldPoliciesIdRequest>
}


/// struct for typed errors of method [`delete_legal_hold_policies_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteLegalHoldPoliciesIdError {
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_legal_hold_policies`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLegalHoldPoliciesError {
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_legal_hold_policies_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLegalHoldPoliciesIdError {
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_legal_hold_policies`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostLegalHoldPoliciesError {
    Status400(models::ClientError),
    Status409(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`put_legal_hold_policies_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PutLegalHoldPoliciesIdError {
    Status409(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}


/// Delete an existing legal hold policy.  This is an asynchronous process. The policy will not be fully deleted yet when the response returns.
pub async fn delete_legal_hold_policies_id(configuration: &configuration::Configuration, params: DeleteLegalHoldPoliciesIdParams) -> Result<(), Error<DeleteLegalHoldPoliciesIdError>> {

    let uri_str = format!("{}/legal_hold_policies/{legal_hold_policy_id}", configuration.base_path, legal_hold_policy_id=crate::apis::urlencode(params.legal_hold_policy_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteLegalHoldPoliciesIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves a list of legal hold policies that belong to an enterprise.
pub async fn get_legal_hold_policies(configuration: &configuration::Configuration, params: GetLegalHoldPoliciesParams) -> Result<models::LegalHoldPolicies, Error<GetLegalHoldPoliciesError>> {

    let uri_str = format!("{}/legal_hold_policies", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.policy_name {
        req_builder = req_builder.query(&[("policy_name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.fields {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("fields".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("fields", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = params.marker {
        req_builder = req_builder.query(&[("marker", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LegalHoldPolicies`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LegalHoldPolicies`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLegalHoldPoliciesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieve a legal hold policy.
pub async fn get_legal_hold_policies_id(configuration: &configuration::Configuration, params: GetLegalHoldPoliciesIdParams) -> Result<models::LegalHoldPolicy, Error<GetLegalHoldPoliciesIdError>> {

    let uri_str = format!("{}/legal_hold_policies/{legal_hold_policy_id}", configuration.base_path, legal_hold_policy_id=crate::apis::urlencode(params.legal_hold_policy_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LegalHoldPolicy`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LegalHoldPolicy`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLegalHoldPoliciesIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Create a new legal hold policy.
pub async fn post_legal_hold_policies(configuration: &configuration::Configuration, params: PostLegalHoldPoliciesParams) -> Result<models::LegalHoldPolicy, Error<PostLegalHoldPoliciesError>> {

    let uri_str = format!("{}/legal_hold_policies", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.post_legal_hold_policies_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LegalHoldPolicy`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LegalHoldPolicy`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostLegalHoldPoliciesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Update legal hold policy.
pub async fn put_legal_hold_policies_id(configuration: &configuration::Configuration, params: PutLegalHoldPoliciesIdParams) -> Result<models::LegalHoldPolicy, Error<PutLegalHoldPoliciesIdError>> {

    let uri_str = format!("{}/legal_hold_policies/{legal_hold_policy_id}", configuration.base_path, legal_hold_policy_id=crate::apis::urlencode(params.legal_hold_policy_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.put_legal_hold_policies_id_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LegalHoldPolicy`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LegalHoldPolicy`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PutLegalHoldPoliciesIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

