/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`get_shield_information_barriers`]
#[derive(Clone, Debug)]
pub struct GetShieldInformationBarriersParams {
    /// Defines the position marker at which to begin returning results. This is used when paginating using marker-based pagination.
    pub marker: Option<String>,
    /// The maximum number of items to return per page.
    pub limit: Option<i64>
}

/// struct for passing parameters to the method [`get_shield_information_barriers_id`]
#[derive(Clone, Debug)]
pub struct GetShieldInformationBarriersIdParams {
    /// The ID of the shield information barrier.
    pub shield_information_barrier_id: String
}

/// struct for passing parameters to the method [`post_shield_information_barriers`]
#[derive(Clone, Debug)]
pub struct PostShieldInformationBarriersParams {
    pub post_shield_information_barriers_request: Option<models::PostShieldInformationBarriersRequest>
}

/// struct for passing parameters to the method [`post_shield_information_barriers_change_status`]
#[derive(Clone, Debug)]
pub struct PostShieldInformationBarriersChangeStatusParams {
    pub post_shield_information_barriers_change_status_request: Option<models::PostShieldInformationBarriersChangeStatusRequest>
}


/// struct for typed errors of method [`get_shield_information_barriers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetShieldInformationBarriersError {
    Status404(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_shield_information_barriers_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetShieldInformationBarriersIdError {
    Status404(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_shield_information_barriers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostShieldInformationBarriersError {
    Status404(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_shield_information_barriers_change_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostShieldInformationBarriersChangeStatusError {
    Status404(models::ClientError),
    Status409(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}


/// Retrieves a list of shield information barrier objects for the enterprise of JWT.
pub async fn get_shield_information_barriers(configuration: &configuration::Configuration, params: GetShieldInformationBarriersParams) -> Result<models::ShieldInformationBarriers, Error<GetShieldInformationBarriersError>> {

    let uri_str = format!("{}/shield_information_barriers", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.marker {
        req_builder = req_builder.query(&[("marker", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ShieldInformationBarriers`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ShieldInformationBarriers`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetShieldInformationBarriersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get shield information barrier based on provided ID.
pub async fn get_shield_information_barriers_id(configuration: &configuration::Configuration, params: GetShieldInformationBarriersIdParams) -> Result<models::ShieldInformationBarrier, Error<GetShieldInformationBarriersIdError>> {

    let uri_str = format!("{}/shield_information_barriers/{shield_information_barrier_id}", configuration.base_path, shield_information_barrier_id=crate::apis::urlencode(params.shield_information_barrier_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ShieldInformationBarrier`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ShieldInformationBarrier`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetShieldInformationBarriersIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Creates a shield information barrier to separate individuals/groups within the same firm and prevents confidential information passing between them.
pub async fn post_shield_information_barriers(configuration: &configuration::Configuration, params: PostShieldInformationBarriersParams) -> Result<models::ShieldInformationBarrier, Error<PostShieldInformationBarriersError>> {

    let uri_str = format!("{}/shield_information_barriers", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.post_shield_information_barriers_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ShieldInformationBarrier`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ShieldInformationBarrier`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostShieldInformationBarriersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Change status of shield information barrier with the specified ID.
pub async fn post_shield_information_barriers_change_status(configuration: &configuration::Configuration, params: PostShieldInformationBarriersChangeStatusParams) -> Result<models::ShieldInformationBarrier, Error<PostShieldInformationBarriersChangeStatusError>> {

    let uri_str = format!("{}/shield_information_barriers/change_status", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.post_shield_information_barriers_change_status_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ShieldInformationBarrier`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ShieldInformationBarrier`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostShieldInformationBarriersChangeStatusError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

