/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2024.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`delete_task_assignments_id`]
#[derive(Clone, Debug)]
pub struct DeleteTaskAssignmentsIdParams {
    /// The ID of the task assignment.
    pub task_assignment_id: String
}

/// struct for passing parameters to the method [`get_task_assignments_id`]
#[derive(Clone, Debug)]
pub struct GetTaskAssignmentsIdParams {
    /// The ID of the task assignment.
    pub task_assignment_id: String
}

/// struct for passing parameters to the method [`get_tasks_id_assignments`]
#[derive(Clone, Debug)]
pub struct GetTasksIdAssignmentsParams {
    /// The ID of the task.
    pub task_id: String
}

/// struct for passing parameters to the method [`post_task_assignments`]
#[derive(Clone, Debug)]
pub struct PostTaskAssignmentsParams {
    pub post_task_assignments_request: Option<models::PostTaskAssignmentsRequest>
}

/// struct for passing parameters to the method [`put_task_assignments_id`]
#[derive(Clone, Debug)]
pub struct PutTaskAssignmentsIdParams {
    /// The ID of the task assignment.
    pub task_assignment_id: String,
    pub put_task_assignments_id_request: Option<models::PutTaskAssignmentsIdRequest>
}


/// struct for typed errors of method [`delete_task_assignments_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteTaskAssignmentsIdError {
    Status404(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_task_assignments_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTaskAssignmentsIdError {
    Status404(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_tasks_id_assignments`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTasksIdAssignmentsError {
    Status404(models::ClientError),
    Status500(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_task_assignments`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostTaskAssignmentsError {
    Status403(models::ClientError),
    Status404(models::ClientError),
    Status500(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`put_task_assignments_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PutTaskAssignmentsIdError {
    Status400(models::ClientError),
    Status404(models::ClientError),
    DefaultResponse(models::ClientError),
    UnknownValue(serde_json::Value),
}


/// Deletes a specific task assignment.
pub async fn delete_task_assignments_id(configuration: &configuration::Configuration, params: DeleteTaskAssignmentsIdParams) -> Result<(), Error<DeleteTaskAssignmentsIdError>> {

    let uri_str = format!("{}/task_assignments/{task_assignment_id}", configuration.base_path, task_assignment_id=crate::apis::urlencode(params.task_assignment_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteTaskAssignmentsIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves information about a task assignment.
pub async fn get_task_assignments_id(configuration: &configuration::Configuration, params: GetTaskAssignmentsIdParams) -> Result<models::TaskAssignment, Error<GetTaskAssignmentsIdError>> {

    let uri_str = format!("{}/task_assignments/{task_assignment_id}", configuration.base_path, task_assignment_id=crate::apis::urlencode(params.task_assignment_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TaskAssignment`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TaskAssignment`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetTaskAssignmentsIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Lists all of the assignments for a given task.
pub async fn get_tasks_id_assignments(configuration: &configuration::Configuration, params: GetTasksIdAssignmentsParams) -> Result<models::TaskAssignments, Error<GetTasksIdAssignmentsError>> {

    let uri_str = format!("{}/tasks/{task_id}/assignments", configuration.base_path, task_id=crate::apis::urlencode(params.task_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TaskAssignments`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TaskAssignments`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetTasksIdAssignmentsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Assigns a task to a user.  A task can be assigned to more than one user by creating multiple assignments.
pub async fn post_task_assignments(configuration: &configuration::Configuration, params: PostTaskAssignmentsParams) -> Result<models::TaskAssignment, Error<PostTaskAssignmentsError>> {

    let uri_str = format!("{}/task_assignments", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.post_task_assignments_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TaskAssignment`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TaskAssignment`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostTaskAssignmentsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates a task assignment. This endpoint can be used to update the state of a task assigned to a user.
pub async fn put_task_assignments_id(configuration: &configuration::Configuration, params: PutTaskAssignmentsIdParams) -> Result<models::TaskAssignment, Error<PutTaskAssignmentsIdError>> {

    let uri_str = format!("{}/task_assignments/{task_assignment_id}", configuration.base_path, task_assignment_id=crate::apis::urlencode(params.task_assignment_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.put_task_assignments_id_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TaskAssignment`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TaskAssignment`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PutTaskAssignmentsIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

